// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           58
// Async Callback:                       1
// Total number of exported functions:  60

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    vesta_x_liquid_staking
    (
        getVegldIdentifier
        getTreasuryWallet
        getFee
        getUnbondingPeriod
        getAdmins
        getUserActionAllowed
        getManagementActionAllowed
        getWhitelistedStakingProviderAddresses
        getAutoDelegateAddress
        getAutoUndelegateAddress
        getLastAsyncCallId
        getAsyncCallStartBlockMap
        getPoolVegldAmount
        getPoolEgldAmount
        getPrestakedEgldAmount
        getPendingRewardEgldAmount
        getPreunstakedEgldAmount
        getUnstakingUsers
        getUnstakingPacks
        getUnbondedEgldAmount
        getTotalUndelegatedEgldAmount
        getTotalOldPreunstakedEgldAmount
        getRecentPreunstakedEgldAmountsMap
        delegateToStakingProvider
        undelegateFromStakingProvider
        withdrawFromStakingProvider
        claimRewardsFromStakingProvider
        prestakePendingRewards
        withdrawFromPrestaked
        removeFailedAsyncCallIds
        userStake
        userUnstake
        userWithdraw
        donate
        issueVegldAndSetAllRoles
        quoteVegld
        quoteEgld
        isOwnerOrAdmin
        isTokenRolesSet
        getVegldPrice
        getEgldPrice
        viewFailedAsyncCallIds
        viewLiquidStakingSettings
        viewUserUnstakingPacks
        setSettings
        setUnbondingPeriod
        setTreasuryWallet
        setFee
        addAdmins
        removeAdmins
        setUserActionAllowed
        setManagementActionAllowed
        addWhitelistedStakingProviderAddresses
        removeWhitelistedStakingProviderAddresses
        setAutoDelegateAddress
        removeAutoDelegateAddress
        setAutoUndelegateAddress
        removeAutoUndelegateAddress
        callBack
    )
}
