////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    vesta_x_liquid_staking
    (
        callBack
        addAdmins
        addWhitelistedStakingProviderAddresses
        claimRewardsFromStakingProvider
        delegateToStakingProvider
        donate
        getAdminActionAllowed
        getAdmins
        getAsyncCallStartBlockMap
        getAutoDelegateAddress
        getAutoUndelegateAddress
        getEgldPrice
        getFee
        getLastAsyncCallId
        getPendingRewardEgldAmount
        getPoolEgldAmount
        getPoolVegldAmount
        getPrestakedEgldAmount
        getPreunstakedEgldAmount
        getRecentPreunstakedEgldAmountsMap
        getTotalOldPreunstakedEgldAmount
        getTotalUndelegatedEgldAmount
        getTreasuryWallet
        getUnbondedEgldAmount
        getUnbondingPeriod
        getUnstakingPacks
        getUnstakingUsers
        getUserActionAllowed
        getVegldIdentifier
        getVegldPrice
        getWhitelistedStakingProviderAddresses
        isOwnerOrAdmin
        isTokenRolesSet
        issueVegldAndSetAllRoles
        prestakePendingRewards
        quoteEgld
        quoteVegld
        removeAdmins
        removeAutoDelegateAddress
        removeAutoUndelegateAddress
        removeFailedAsyncCallIds
        removeWhitelistedStakingProviderAddresses
        setAdminActionAllowed
        setAutoDelegateAddress
        setAutoUndelegateAddress
        setFee
        setSettings
        setTreasuryWallet
        setUnbondingPeriod
        setUserActionAllowed
        stake
        undelegateFromStakingProvider
        unstake
        viewFailedAsyncCallIds
        viewLiquidStakingSettings
        viewUserUnstakingPacks
        withdraw
        withdrawFromPrestaked
        withdrawFromStakingProvider
    )
}
