////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    vesta_x_liquid_staking
    (
        callBack
        addAdmins
        addWhitelistedStakingProviderAddresses
        adminClaimRewards
        adminDelegate
        adminUndelegate
        adminWithdraw
        donate
        getAdminActionAllowed
        getAdmins
        getAutoDelegateAddress
        getAutoUndelegateAddress
        getEgldPrice
        getFee
        getPoolEgldAmount
        getPoolVegldAmount
        getPrestakedEgldAmount
        getPreunstakedEgldAmount
        getTreasuryWallet
        getUnbondedEgldAmount
        getUnbondingPeriod
        getUnstakingEgldAmount
        getUnstakingPacks
        getUnstakingUsers
        getUserActionAllowed
        getVegldIdentifier
        getVegldPrice
        getWhitelistedStakingProviderAddresses
        isOwnerOrAdmin
        isTokenRolesSet
        issueVegldAndSetAllRoles
        quoteEgld
        quoteVegld
        removeAdmins
        removeAutoDelegateAddress
        removeAutoUndelegateAddress
        removeWhitelistedStakingProviderAddresses
        setAdminActionAllowed
        setAutoDelegateAddress
        setAutoUndelegateAddress
        setFee
        setSettings
        setTreasuryWallet
        setUnbondingPeriod
        setUserActionAllowed
        stake
        unstake
        viewLiquidStakingSettings
        viewUserUnstakingPacks
        withdraw
    )
}
