[package]
name = "vesta-x-liquid-staking"
version = "0.1.0"
authors = [ "Ice <icegriffin1122@gmail.com>",]
edition = "2018"
publish = false
license = "GPL3 or later"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.36.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.0"
