////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    valar_liquid_staking
    (
        callBack
        addAdmins
        adminDelegate
        adminMoveTreasury
        adminRedelegateRewards
        adminUndelegate
        adminWithdraw
        donate
        getAdminActionAllowed
        getAdmins
        getEgldPrice
        getFee
        getPoolEgldAmount
        getPoolValarAmount
        getPrestakedEgldAmount
        getPreunstakedEgldAmount
        getTreasuryWallet
        getUnbondedEgldAmount
        getUnbondingPeriod
        getUnstakingEgldAmount
        getUnstakingPacks
        getUnstakingUsers
        getUserActionAllowed
        getValarIdentifier
        getValarPrice
        isOwnerOrAdmin
        issueValarAndSetAllRoles
        quoteEgld
        quoteValar
        removeAdmins
        setAdminActionAllowed
        setFee
        setSettings
        setTreasuryWallet
        setUnbondingPeriod
        setUserActionAllowed
        stake
        unstake
        viewLiquidStakingSettings
        withdraw
    )
}
