////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    valar_liquid_staking
    (
        callBack
        addAdmins
        adminClaimRewards
        adminDelegate
        adminRedelegateRewards
        adminTransferEgld
        adminUndelegate
        adminWithdraw
        donate
        getAdminActionAllowed
        getAdmins
        getEgldPrice
        getPoolEgldAmount
        getPoolValarAmount
        getPrestakedEgldAmount
        getPreunstakedEgldAmount
        getTreasuryWallet
        getUnbondedEgldAmount
        getUnbondingPeriod
        getUnstakingEgldAmount
        getUnstakingPacks
        getUnstakingUsers
        getUserActionAllowed
        getValarIdentifier
        getValarPrice
        issueValarAndSetAllRoles
        quoteEgld
        quoteValar
        removeAdmins
        setAdminActionAllowed
        setSettings
        setTreasuryWallet
        setUnbondingPeriod
        setUserActionAllowed
        stake
        unstake
        updateMainPool
        withdraw
    )
}
