////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    vesta_x_liquid_staking
    (
        callBack
        addAdmins
        adminDelegate
        adminMoveTreasury
        adminRedelegateRewards
        adminUndelegate
        adminWithdraw
        donate
        getAdminActionAllowed
        getAdmins
        getEgldPrice
        getFee
        getPoolEgldAmount
        getPoolVegldAmount
        getPrestakedEgldAmount
        getPreunstakedEgldAmount
        getTreasuryWallet
        getUnbondedEgldAmount
        getUnbondingPeriod
        getUnstakingEgldAmount
        getUnstakingPacks
        getUnstakingUsers
        getUserActionAllowed
        getVegldIdentifier
        getVegldPrice
        isOwnerOrAdmin
        issueVegldAndSetAllRoles
        quoteEgld
        quoteVegld
        removeAdmins
        setAdminActionAllowed
        setFee
        setSettings
        setTreasuryWallet
        setUnbondingPeriod
        setUserActionAllowed
        stake
        unstake
        viewLiquidStakingSettings
        withdraw
    )
}
