[package]
name = "vesta-x-liquid-staking-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.vesta-x-liquid-staking]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.36.0"
